{{- if .Values.database.service.class -}}
# svcat bind app-db --name db-binding --secret-name db-secret
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ include "ruby-with-binding.fullname" . }}-db-binding
spec:
  instanceRef:
    name: {{ include "ruby-with-binding.fullname" . }}-db-instance
  secretName: {{ template "ruby-with-binding.fullname" . }}-db-secret
{{- end -}}