{{- if .Values.database.service.class -}}
# svcat provision app-db --class cleardb --plan spark
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ include "ruby-with-binding.fullname" . }}-db-instance
spec:
  clusterServiceClassExternalName: {{ .Values.database.service.class }}
  clusterServicePlanExternalName: {{ .Values.database.service.plan }}
{{- end -}}