---
meta:
  name:    show-me-secrets
  target:  ohio-sw
  url:     https://ci2.starkandwayne.com
  team:    starkandwayne

  initial_version: 0.1.0

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  google:
    serviceaccount: ((gcp-service-account-knative-experiments))
    gcloud_project: ((gke-project-name))
    gcloud_cluster: ((gke-cluster-name))
    gcloud_zone:    ((gke-cluster-zone))
    ca_cert:        ((helm-ca))
    client_cert:    ((helm-tiller-cert))
    client_key:     ((helm-tiller-key))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-1
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))
    charts_uri:  s3://helm.starkandwayne.com/charts

  github:
    owner:  starkandwayne
    repo:   show-me-secrets
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  dockerhub:
    username:   ((docker-hub-username))
    password:   ((docker-hub-password))
    repository: ((docker-hub-username))/show-me-secrets

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#show-me-secrets"
